[build]
# Use the Docker builder
builder = "dockerfile"
# Specify the Dockerfile path
dockerfilePath = "Dockerfile"

[deploy]
# Configure scaling options and health check
healthcheckPath = "/-/healthy"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
