[build]
# Use the Docker builder
builder = "DOCKERFILE"
# Specify the Dockerfile path
dockerfilePath = "Dockerfile"

[deploy]
# Configure scaling options if needed
healthcheckPath = "/-/healthy"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
