// genbrand renders internal/shim/brand.go from the repo-root brand.json — the
// one source of truth shared with client/src/lib/brand.ts and
// server/src/lib/brand.ts. Run via `go generate ./internal/...` from
// opengraph-service/ — `go generate ./...` also matches this cmd/genbrand
// package itself and corrupts its build directory with the generator's own
// output.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
)

type brand struct {
	AppName  string   `json:"appName"`
	Wordmark []string `json:"wordmark"`
}

const tmpl = `// Code generated by genbrand from %s; DO NOT EDIT.

package shim

//go:generate go run ../../cmd/genbrand -in ../../../brand.json -out brand.go

const AppName = %q

// AppNameWordmarkHTML is the footer's two-tone lockup — first syllable in the
// body colour, second in {{TEXT_ACCENT}}.
const AppNameWordmarkHTML = %q
`

func main() {
	in := flag.String("in", "", "path to brand.json")
	out := flag.String("out", "", "path to write the generated Go file")
	flag.Parse()

	data, err := os.ReadFile(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var b brand
	if err := json.Unmarshal(data, &b); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if len(b.Wordmark) != 2 {
		fmt.Fprintf(os.Stderr, "brand.json wordmark must have exactly 2 syllables, got %d\n", len(b.Wordmark))
		os.Exit(1)
	}

	wordmarkHTML := fmt.Sprintf("%s<span>%s</span>", b.Wordmark[0], b.Wordmark[1])
	content := fmt.Sprintf(tmpl, *in, b.AppName, wordmarkHTML)
	if err := os.WriteFile(*out, []byte(content), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
