import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { registerSW } from "virtual:pwa-register";

import { queryClient } from "./api/queryClient";
import { AppLayout } from "./AppLayout";
import { BounceLogosProvider } from "./components/BounceLogosContext";
import { InstallPromptProvider } from "./components/InstallPromptContext";
import navyfragenTheme from "./Theme";

import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <MantineProvider defaultColorScheme="auto" theme={navyfragenTheme}>
      <Notifications position="bottom-right" autoClose={5000} limit={3} />
      <BrowserRouter>
        <QueryClientProvider client={queryClient}>
          <InstallPromptProvider>
            <BounceLogosProvider>
              <AppLayout />
              <ReactQueryDevtools initialIsOpen={false} />
            </BounceLogosProvider>
          </InstallPromptProvider>
        </QueryClientProvider>
      </BrowserRouter>
    </MantineProvider>
  </React.StrictMode>
);

// Register the Workbox service worker generated by vite-plugin-pwa.
//
// The plugin is dev-aware (devOptions.enabled = false in vite.config.ts), so
// in development it uninstalls any stale service worker before the app boots —
// closing the race where a leftover production SW could intercept TanStack
// Query's first fetches on a fresh reload. In production it registers the
// generated /sw.js (push notifications, offline app shell).
registerSW({ immediate: true });
