version: "3.8"
services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
